# ==========================================
# = SERVER CONFIG
# ==========================================
server.port=8081

# ==========================================
# = DATABASE CONFIGURATION
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/food_delivery_db
spring.datasource.username=root
spring.datasource.password=Raunaksingh@1000

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# = JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ==========================================
# = JWT CONFIGURATION
# ==========================================
jwt.secret=a3f8c2d1e94b7056f3a1c8e2d4b6f9a0c1e3d5b7f2a4c6e8d0b2f4a6c8e0d2b4f6a8c0e2d4b6f8a0c2e4d6b8f0a2c4e6d8b0f2a4c6e8d0b2f4a6c8e0d2b4f6

# ==========================================
# = LOGGING
# ==========================================
logging.level.org.springframework.security=DEBUG